"""Make diagnosis nullable in medical_record

Revision ID: c2f5047952f2
Revises: 86e65dd30485
Create Date: 2025-04-30 02:47:27.841791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f5047952f2'
down_revision = '86e65dd30485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('coding_system', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('medications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medications', sa.VARCHAR(length=1000), nullable=True))
        batch_op.alter_column('diagnosis',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    op.drop_table('medication')
    op.drop_table('diagnosis')
    # ### end Alembic commands ###
